version: '2'
services:
  prototon:
    stdin_open: true
    tty: true
    build: .
    image: prototon
    ports:
      - "80:8080"
    volumes:
      - "./index.js:/src/index.js"
      - "./behaviors/:/src/behaviors"
      - prototon_node_modules:/src/node_modules/
volumes:
  prototon_node_modules: {}
